# The overall format is standard TOML format, v0.5.0.
modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="elytra_physics" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="assets/elytra_physics/icon.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.elytra_physics]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="CLIENT"
# Here's another dependency
[[dependencies.elytra_physics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.5,1.21.1]"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"